api_keys:
  slack: "$SLACK_TOKEN"
  pagerduty:
    org: "$PAGERDUTY_ORG"
    key: "$PAGERDUTY_KEY"

groups:
  - name: platform-engineering-help
    schedules:
      - PCLYMC8
  - name: data-help
    schedules:
      - PK08WGZ
  - name: analytics-help
    schedules:
      - PK08WGZ
  - name: it-help
    schedules:
      - PBC8G5I
  - name: growth-engineering-help
    schedules:
      - PLK5L2Y
  - name: supply-chain-engineering-help
    schedules:
      - PIMQ3SN
  # TODO(serhalp) Remove these two as part of cleanup step of
  # https://www.pivotaltracker.com/story/show/178790883.
  - name: application-engineering-help
    schedules:
      - P61VATU
  - name: application-engineering-help-backup
    schedules:
      - P8MOV3F
