FROM goodeggs/platform-base:2.6.0 as development

ARG GO_IMPORT_PATH
ENV GOPATH=/gopath
ENV PATH=$GOPATH/bin:/usr/local/go/bin:$PATH
WORKDIR /gopath/src/${GO_IMPORT_PATH}
RUN true \
  && install_packages build-essential \
  && chown -R docker:docker /gopath \
  && mkdir /.cache \
  && chown docker:docker /.cache

COPY --chown=docker:docker .go-version ./
# Golang download paths don't include patch level 0!
RUN curl -sSL "https://dl.google.com/go/go$(cat .go-version | sed 's/[.]0$//').linux-amd64.tar.gz" | sudo tar -C /usr/local -xz
