version: "3"

services:
  runner:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    command: ["sh", "-c", "echo 'READY PLAYER ONE'; sleep 90000"]
    volumes:
      - .:/app
    env_file:
      - .ci-runner.env
