name: Helm Chart Release

on:
  push:
    branches:
      - main

jobs:

  changes:
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.filter.outputs.charts }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            charts:
              - 'charts/pagerbot/Chart.yaml'
              - 'charts/pagerbot/**/*'

  release_chart:
    name: Release Chart
    runs-on: ubuntu-latest
    needs:
      - changes
    if: |
      (needs.changes.outputs.charts == 'true')
    permissions:
      contents: write # needed to write releases

    steps:

      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_RELEASE_NAME_TEMPLATE: "helm-chart-{{ .Version }}"
